version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html/public
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: 
      DB_USERNAME: 
      DB_PASSWORD: 
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
