name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "DATABASE_HOST=${{ secrets.DC_BOT_TOKEN }}" >> .env
          echo "DATABASE_USER=${{ secrets.DC_BOT_PUBLIC_KEY }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DC_APP_ID }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DC_BOT_SECRET_KEY }}" >> .env

      - name: Create Nginx Config File
        run: |
          mkdir -p public/nginx  # Asegúrate de crear el directorio si no existe
          echo 'server {' > public/nginx/default.conf
          echo '    listen 80;' >> public/nginx/default.conf
          echo '    server_name localhost;' >> public/nginx/default.conf
          echo '' >> public/nginx/default.conf
          echo '    root /var/www/html/public;' >> public/nginx/default.conf
          echo '    index index.php index.html index.htm;' >> public/nginx/default.conf
          echo '' >> public/nginx/default.conf
          echo '    location / {' >> public/nginx/default.conf
          echo '        try_files $uri $uri/ /index.php?$query_string;' >> public/nginx/default.conf
          echo '    }' >> public/nginx/default.conf
          echo '' >> public/nginx/default.conf
          echo '    location ~ \.php$ {' >> public/nginx/default.conf
          echo '        include fastcgi_params;' >> public/nginx/default.conf
          echo '        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;' >> public/nginx/default.conf
          echo '        fastcgi_pass unix:/var/run/php/php-fpm.sock;' >> public/nginx/default.conf
          echo '        fastcgi_index index.php;' >> public/nginx/default.conf
          echo '    }' >> public/nginx/default.conf
          echo '' >> public/nginx/default.conf
          echo '    location ~ /\.ht {' >> public/nginx/default.conf
          echo '        deny all;' >> public/nginx/default.conf
          echo '    }' >> public/nginx/default.conf
          echo '}' >> public/nginx/default.conf

      - name: Install tree
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Show directory tree
        run: tree

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Container Build and Push
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/technokey-asses-img:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/technokey-asses-img:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIV_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/technokey-asses-img:latest
            docker stop technokey-asses-container
            docker rm technokey-asses-container
            docker run -d --name technokey-asses-container -p 8002:80 nicodav28/technokey-asses-img:latest

            if docker ps | grep technokey-asses-container; then
              echo "Container is running successfully"
            else
              echo "Failed to start container"
              exit 1
            fi

      - name: Prune System
        run: "echo y | docker system prune -a"
